//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopenhagenAirport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int ID { get; set; }
        public int AirlineOwner { get; set; }
        public int AirlineOperator { get; set; }
        public string DepartureIATA { get; set; }
        public string DestinationIATA { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Airline Airline1 { get; set; }
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
    }
}
