CREATE TABLE Airports
(
	IATA VARCHAR(3) PRIMARY KEY NOT NULL,
	Name VARCHAR(150) NOT NULL,
	City VARCHAR(150) NOT NULL,
	Country VARCHAR(150) NOT NULL,
)

CREATE TABLE Airlines
(
	ID INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name VARCHAR(150) NOT NULL,
)

CREATE TABLE Routes
(
	ID INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
	AirlineOwner INTEGER NOT NULL,
	AirlineOperator INTEGER NOT NULL,
	DepartureIATA VARCHAR(3) NOT NULL,
	DestinationIATA VARCHAR(3) NOT NULL,

	FOREIGN KEY (AirlineOwner) REFERENCES Airlines(ID),
	FOREIGN KEY (AirlineOperator) REFERENCES Airlines(ID),
	FOREIGN KEY (DepartureIATA) REFERENCES Airports(IATA),
	FOREIGN KEY (DestinationIATA) REFERENCES Airports(IATA),
)